//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookView
    {
        public int 藏书号 { get; set; }
        public string 书籍标题 { get; set; }
        public string 作者 { get; set; }
        public bool 已借出 { get; set; }
        public string 备注 { get; set; }
    }
}
