//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.Records = new HashSet<Record>();
        }
    
        public int BookID { get; set; }
        public int BookInfoID { get; set; }
        public bool IsRent { get; set; }
        public string Remark { get; set; }
    
        public virtual BookInfo BookInfo { get; set; }
        public virtual ICollection<Record> Records { get; set; }
    }
}
