//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookInfo
    {
        public BookInfo()
        {
            this.Books = new HashSet<Book>();
        }
    
        public int BookInfoID { get; set; }
        public string Title { get; set; }
        public string ISBN { get; set; }
        public string Author { get; set; }
        public string Press { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public string Brief { get; set; }
        public byte[] Cover { get; set; }
    
        public virtual Author Author1 { get; set; }
        public virtual ICollection<Book> Books { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual Press Press1 { get; set; }
    }
}
