//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int RecordID { get; set; }
        public int UserID { get; set; }
        public int BookID { get; set; }
        public System.DateTime OutDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string Remark { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
