//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserView
    {
        public int 用户编号 { get; set; }
        public string 账户 { get; set; }
        public string 姓名 { get; set; }
        public Nullable<int> 年龄 { get; set; }
        public string 性别 { get; set; }
        public string 电话 { get; set; }
        public string 电邮 { get; set; }
        public string 地址 { get; set; }
        public string 分组 { get; set; }
        public bool 管理员 { get; set; }
        public int 最大借阅数 { get; set; }
    }
}
